---
title: "2019 check-ex-spec study"
---
# init
```{r}
library(ggplot2)
library(dplyr)
library(pwr)
library(reshape2)
library(vcd)
library(data.table)
options(scipen=5)
setwd("~/repos/experimentr/analysis/")
```
# data
```{r}
data <- read.csv("data.csv")
data <- mutate(data, ocavg=oc/octotal, ucavg=uc/uctotal)

hw2_directedtree <- subset(data, taskID=="hw2_directedtree_easy")
hw2_ring <- subset(data, taskID=="hw2_ring_easy")
hw2_spanningtree <- subset(data, taskID=="hw2_spanningtree_easy")
hw2_undirectedtree <- subset(data, taskID=="hw2_undirectedtree_easy")

hw3_event <- subset(data, taskID=="hw3_goatswolves_event_easy")
hw3_final <- subset(data, taskID=="hw3_goatswolves_final_easy")
hw3_initial <- subset(data, taskID=="hw3_goatswolves_initial_easy")

hw4_deadlock <- subset(data, taskID=="hw4_statemachine_deadlock_easy")
hw4_deterministic <- subset(data, taskID=="hw4_statemachine_deterministic_easy")
hw4_livelock <- subset(data, taskID=="hw4_statemachine_livelock_easy")
hw4_reachable <- subset(data, taskID=="hw4_statemachine_reachable_easy")
```
# Best UC scores for each distinct user
```{r}
bestUC <-function(df) {
  DT <- data.table(df)
  DT <- DT[, max(ucavg), by = email]
  ggplot(data=DT, aes(DT$V1)) + labs(x="Best UC score", y="Number of students", title=df$taskID) + geom_histogram(binwidth = .1)
}

bestUC(hw2_directedtree)
bestUC(hw2_ring)
bestUC(hw2_spanningtree)
bestUC(hw2_undirectedtree)

bestUC(hw3_event)
bestUC(hw3_final)
bestUC(hw3_initial)

bestUC(hw4_deadlock)
bestUC(hw4_deterministic)
bestUC(hw4_livelock)
bestUC(hw4_reachable)
```
# Proportion of users catching the OC per task
```{r}
bestOC <-function(df) {
  DT <- data.table(df)
  DT <- DT[, max(ocavg), by = email]
  print(df$taskID[1])
  nrow(subset(DT, V1>0))/nrow(DT)
}

bestOC(hw2_directedtree)
bestOC(hw2_ring)
bestOC(hw2_spanningtree)
bestOC(hw2_undirectedtree)

bestOC(hw3_event)
bestOC(hw3_final)
bestOC(hw3_initial)

bestOC(hw4_deadlock)
bestOC(hw4_deterministic)
bestOC(hw4_livelock)
bestOC(hw4_reachable)
```
