node src/convert.js results/data.json modules/t01.html  >> results/data.csv
node src/convert.js results/data.json modules/t02.html  >> results/data.csv
node src/convert.js results/data.json modules/t03.html  >> results/data.csv
node src/convert.js results/data.json modules/t04.html  >> results/data.csv
node src/convert.js results/data.json modules/t05.html  >> results/data.csv
node src/convert.js results/data.json modules/t06.html  >> results/data.csv
node src/convert.js results/data.json modules/t07.html  >> results/data.csv
node src/convert.js results/data.json modules/t08.html  >> results/data.csv
node src/convert.js results/data.json modules/t09.html  >> results/data.csv
node src/convert.js results/data.json modules/t10.html >> results/data.csv
node src/convert.js results/data.json modules/t11.html >> results/data.csv
